version: "3.2"

x-common-env: &common-env
  RPC_HOST: https://rpc-apothem.xinfin.yodaplus.net
  FROM_BLOCK: 32463078
  PASS: ${PASS}

services:
  clip_kick:
    environment:
      <<: *common-env
      FROM: ${FROM_CLIP_KICK}
      KEY: ${KEY_CLIP_KICK}
      ILK: XDC-C
    command: ./scripts/start_clip_kick.sh

  flap_kick:
    environment:
      <<: *common-env
      FROM: ${FROM_FLAP_KICK}
      KEY: ${KEY_FLAP_KICK}
    command: ./scripts/start_flap_kick.sh

  flop_kick:
    environment:
      <<: *common-env
      FROM: ${FROM_FLOP_KICK}
      KEY: ${KEY_FLOP_KICK}
    command: ./scripts/start_flop_kick.sh

  clip_bid:
    environment:
      <<: *common-env
      FROM: ${FROM_CLIP_BID}
      KEY: ${KEY_CLIP_BID}
      ILK: XDC-C
      MAX_AUCTIONS: 10
      BID_CHECK_INTERVAL: 60
      BID_DELAY: 10
      RETURN_GEM_INTERVAL: 60
      VAT_DAI_TARGET: 20
    command: ./scripts/start_clip_bid.sh

  flap_bid:
    environment:
      <<: *common-env
      FROM: ${FROM_FLAP_BID}
      KEY: ${KEY_FLAP_BID}
      BID_CHECK_INTERVAL: 60
      BID_DELAY: 10
    command: ./scripts/start_flap_bid.sh

  flop_bid:
    environment:
      <<: *common-env
      FROM: ${FROM_FLOP_BID}
      KEY: ${KEY_FLOP_BID}
      BID_CHECK_INTERVAL: 60
      BID_DELAY: 10
      VAT_DAI_TARGET: 20
    command: ./scripts/start_flop_bid.sh
